services:
  - type: web
    name: telegram-jobs-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false 