services:
  - type: database
    name: telegram-jobs-db
    region: frankfurt
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: telegram_bot
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: jobs_db

  - type: worker
    name: telegram-jobs-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-jobs-db
          property: connectionString 